import React from 'react'
import LabelDemo from '../components/Label'
import GoogleButton from '../components/GoogleButton'
import SignInForm from '../components/SignInForm'
import SignUpForm from '../components/SignUpForm'
import AccountTabs from '../components/AccountTabs'
import DiscordButton from '../components/DiscordButton'
import TwitterButton from '../components/TwitterButton'
import ConfirmationButton from '../components/ConfirmationButton'
import ToastButton from '../dashboard/components/ToastButton'
import Navbar from '../components/Navbar'
import AuthForm from '../components/AuthForm'
import AccountForm from '../components/AccountForm'

export const metadata = {
    title: 'ThenSignin',
    description: 'Generated by create next app',
}
type Props = {}

const page = (props: Props) => {
    return (
        <>
            <nav>
                <Navbar />
            </nav>
            {/*<div className='flex justify-center items-center h-[100vh] w-full text-xs md:text-base' id='signinPage'>

                <AccountTabs
                    firstTab='Sign In'
                    secondTab='Create Account'
                    firstTabContent={
                        <>
                            <div className='flex flex-col items-center gap-3 '>
                                <SignInForm />
                                <GoogleButton />
                                <DiscordButton />
                                <TwitterButton />

                            </div>
                        </>
                    }
                    secondTabContent={
                        <>
                            <div className='flex flex-col items-center gap-3 '>
                                <SignUpForm />
                                <GoogleButton />
                                <DiscordButton />
                                <TwitterButton />
                            </div>
                        </>
                    }
                />

                </div>*/}
            <div className='flex justify-center items-center w-full h-screen'>
                <AuthForm />
                
            </div>
        </>

    )
}


export default page
