import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { AvatarProvider } from '@/context/AvatarContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ThenDigital',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AvatarProvider>
        <body className={inter.className}>{children}</body>
      </AvatarProvider>
    </html>
  )
}
