import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { AvatarProvider } from '@/context/AvatarContext'
import { SessionProvider } from 'next-auth/react';
import NextAuthProvider from './components/NextAuthProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ThenDigital',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
      className={`${inter.className} scroll-smooth`}
    >
      <body>
        <NextAuthProvider>
          <AvatarProvider>
            <main className='grow'>
              {children}
            </main>
          </AvatarProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
