import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'ThenDashboard',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en"
            className={`${inter.className} scroll-smooth`}
        >
            <body>
                <main className='grow'>
                    {children}
                </main>
            </body>
        </html>
    )
}